version: '3.7'

services:
  tracking-performance:
    container_name: tracking-performance
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '$PORT:$PORT'
    env_file: .env
    restart: always
